# ------ root_path/dataset_name ------
root_path: 'DATA'

# ------ Basic Config ------
shots: 1
backbone: 'RN50'
dataset: 'fewsol'
only_test: False

lr: 0.001 #0.0008
# lr: 0.0009
augment_epoch: 10
train_epoch: 250

alpha: 0.9
beta: 17

adapter: 'conv-3x'
train_vis_mem_only: False

losses: ['L1', 'L2', 'L3']
