# ------ root_path/dataset_name ------
root_path: 'DATA'

# ------ Basic Config ------
shots: 1
backbone: 'RN50'
dataset: 'oxford_pets'
only_test: False

lr: 0.001
augment_epoch: 10
train_epoch: 250 #2000

alpha: 0.4
beta: 18

adapter: 'conv-2x'
train_vis_mem_only: True

losses: ['L1', 'L2', 'L3']
