# ------ root_path/dataset_name ------
root_path: 'DATA'

# ------ Basic Config ------
shots: 16
backbone: 'RN50'
dataset: 'sun397'
only_test: False

lr: 0.0001
augment_epoch: 10
train_epoch: 2000

alpha: 1
beta: 11

adapter: 'conv-2x'
train_vis_mem_only: True

losses: ['L1', 'L2', 'L3']
